# Generated by Django 3.1.5 on 2021-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetflow',
            name='label',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packetflow',
            name='port_dst',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packetflow',
            name='port_src',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='packetflow',
            name='ip_dst',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='packetflow',
            name='ip_src',
            field=models.TextField(default=''),
        ),
    ]
