# Generated by Django 3.1.5 on 2021-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210130_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('ifInOctets11', models.TextField(default='')),
                ('ifOutOctets11', models.TextField(default='')),
                ('ifoutDiscards11', models.TextField(default='')),
                ('ifInUcastPkts11', models.TextField(default='')),
                ('ifInNUcastPkts11', models.TextField(default='')),
                ('ifInDiscards11', models.TextField(default='')),
                ('ifOutUcastPkts11', models.TextField(default='')),
                ('ifOutNUcastPkts11', models.TextField(default='')),
                ('tcpOutRsts', models.TextField(default='')),
                ('tcpInSegs', models.TextField(default='')),
                ('tcpOutSegs', models.TextField(default='')),
                ('tcpPassiveOpens', models.TextField(default='')),
                ('tcpRetransSegs', models.TextField(default='')),
                ('tcpCurrEstab', models.TextField(default='')),
                ('tcpEstabResets', models.TextField(default='')),
                ('tcpActiveOpens', models.TextField(default='')),
                ('udpInDatagrams', models.TextField(default='')),
                ('udpOutDatagrams', models.TextField(default='')),
                ('udpInErrors', models.TextField(default='')),
                ('udpNoPorts', models.TextField(default='')),
                ('ipInReceives', models.TextField(default='')),
                ('ipInDelivers', models.TextField(default='')),
                ('ipOutRequests', models.TextField(default='')),
                ('ipOutDiscards', models.TextField(default='')),
                ('ipInDiscards', models.TextField(default='')),
                ('ipForwDatagrams', models.TextField(default='')),
                ('ipOutNoRoutes', models.TextField(default='')),
                ('ipInAddrErrors', models.TextField(default='')),
                ('icmpInMsgs', models.TextField(default='')),
                ('icmpInDestUnreachs', models.TextField(default='')),
                ('icmpOutMsgs', models.TextField(default='')),
                ('icmpOutDestUnreachs', models.TextField(default='')),
                ('icmpInEchos', models.TextField(default='')),
                ('icmpOutEchoReps', models.TextField(default='')),
            ],
        ),
    ]
