# Generated by Django 3.1.5 on 2021-02-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_agentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snmpdata',
            old_name='ifoutDiscards11',
            new_name='ifOutDiscards11',
        ),
    ]
