# Generated by Django 3.1.7 on 2021-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210211_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_src', models.TextField()),
                ('port_src', models.TextField()),
                ('ip_dst', models.TextField()),
                ('port_dst', models.TextField()),
                ('protocol', models.TextField()),
                ('confidence', models.IntegerField()),
            ],
        ),
    ]
