# Generated by Django 3.1.7 on 2021-02-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_trafficdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficdata',
            name='agent_id',
            field=models.TextField(default=''),
        ),
    ]
