# Generated by Django 3.1.7 on 2021-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_trafficdata_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='port_dst',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='port_src',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='protocol',
            field=models.IntegerField(),
        ),
    ]
