# Generated by Django 3.1.7 on 2021-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210225_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketFlow',
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='monitor',
            field=models.IntegerField(default=0),
        ),
    ]
