# Generated by Django 3.1.5 on 2021-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snmp_mib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifInOctets11', models.IntegerField()),
                ('ifOutOctets11', models.IntegerField()),
                ('ifOutDiscards11', models.IntegerField()),
                ('ifInUcastPkts11', models.IntegerField()),
                ('ifInNUcastPkts11', models.IntegerField()),
                ('ifInDiscards11', models.IntegerField()),
                ('ifOutUcastPkts11', models.IntegerField()),
                ('ifOutNUcastPkts11', models.IntegerField()),
                ('tcpOutRsts', models.IntegerField()),
                ('tcpInSegs', models.IntegerField()),
                ('tcpOutSegs', models.IntegerField()),
                ('tcpPassiveOpens', models.IntegerField()),
                ('tcpRetransSegs', models.IntegerField()),
                ('tcpCurrEstab', models.IntegerField()),
                ('tcpEstabResets', models.IntegerField()),
                ('tcpActiveOpens', models.IntegerField()),
                ('udpInDatagrams', models.IntegerField()),
                ('udpOutDatagrams', models.IntegerField()),
                ('udpInErrors', models.IntegerField()),
                ('udpNoPorts', models.IntegerField()),
                ('ipInReceives', models.IntegerField()),
                ('ipInDelivers', models.IntegerField()),
                ('ipOutRequests', models.IntegerField()),
                ('ipOutDiscards', models.IntegerField()),
                ('ipInDiscards', models.IntegerField()),
                ('ipForwDatagrams', models.IntegerField()),
                ('ipOutNoRoutes', models.IntegerField()),
                ('ipInAddrErrors', models.IntegerField()),
                ('icmpInMsgs', models.IntegerField()),
                ('icmpInDestUnreachs', models.IntegerField()),
                ('icmpOutMsgs', models.IntegerField()),
                ('icmpOutDestUnreachs', models.IntegerField()),
                ('icmpInEchos', models.IntegerField()),
                ('icmpOutEchoReps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
            ],
        ),
    ]
