# Generated by Django 3.1.7 on 2021-02-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='snmp_mib',
        ),
        migrations.DeleteModel(
            name='test_model',
        ),
    ]
